// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package sensor

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("sensor", "sensor", asset.ModuleFieldsPri, AssetSensor); err != nil {
		panic(err)
	}
}

// AssetSensor returns asset data.
// This is the base64 encoded zlib format compressed contents of module/sensor.
func AssetSensor() string {
	return "eJx8kEGugyAYhPecYuLeC7B4u3eCdwKeTBsiCAFMy+0bBRtjrbOc38z3SY+RRSJxSj4KIJtsKdH9lZTpWp86AURaqkSJf2YlAM00RBOy8ZPEjwDQvobzerYUwM3Q6iTXW49JOUpY1zbXFsglUOIe/RxaczK8xL5t4JijGbaFPeWKdE5bcvy1LV9Mqs3n+FFkL8OncmF9lH2qzsjy8FEfbhfwJb91sELFKwAA///E2Xy2"
}
